### ISSUE TITLE
Automate build

### ISSUE THREAD

**Issue by paulodamaso** [fabriciofx/cactoos-jdbc#12]
There is no automate building provider, let's use [rultor](http://doc.rultor.com/) to do this automation

**Comment by fabriciofx** [comment]
@paulodamaso I agree. Can you submit a PR to achieve it?

**Comment by paulodamaso** [comment]
@rultor hello

**Comment by fabriciofx** [comment]
@paulodamaso This PR has been already merged. Can you close this issue?
