### ISSUE TITLE
KeydQuery, is it a typo?

### ISSUE THREAD

**Issue by mdbs99** [fabriciofx/cactoos-jdbc#3]
I believe this class, [KeydQuery](https://github.com/fabriciofx/cactoos-jdbc/blob/master/src/main/java/com/github/fabriciofx/cactoos/jdbc/query/KeydQuery.java), is a typo. 

Should it be `KeyedQuery`?

**Comment by fabriciofx** [comment]
@mdbs99 It's a typo! I'll fix it now. Thanks!

**Comment by fabriciofx** [comment]
Closed by e20c9cbbdbc4f25bc73bbf7dffff52b8eafa3c3b
