### ISSUE TITLE
Regex in ParsedSql

### ISSUE THREAD

**Issue by Lollipopster** [fabriciofx/cactoos-jdbc#4]
In ParsedSql class you have the following pattern
Pattern find = Pattern.compile("(?<!')(:[\\w]*)(?!')");
Then you use substring(1) from matched strings , maybe it would be better to use this pattern instead
Pattern.compile("(?<!'):([\\w]*)(?!')")
And then 
while (matcher.find()) {
            fields.add(matcher.group(1));
        }

**Comment by fabriciofx** [comment]
Hi @Lollipopster! Sorry for the delay! I've changed the regex in ParsedSql as suggested, but it fails at my [SimpleQueryTest](https://github.com/fabriciofx/cactoos-jdbc/blob/master/src/test/java/com/github/fabriciofx/cactoos/jdbc/query/SimpleQueryTest.java). SimpleQueryTest uses ParsedSql.

**Comment by fabriciofx** [comment]
@Lollipopster As this change can't work fine, I'll close this issue.
