### ISSUE TITLE
Release it to sonatype

### ISSUE THREAD

**Issue by smallcreep** [fabriciofx/cactoos-jdbc#5]
For use it in project we should have download jar from [sonatype](https://search.maven.org/) repository.

**Comment by fabriciofx** [comment]
@smallcreep I agree! I've been working on it, but I had some problems (I'm newbie in publish my artifacts to sonatype). But I'll try it again. Thanks!

**Comment by smallcreep** [comment]
@fabriciofx Can I help you with it?

**Comment by fabriciofx** [comment]
@smallcreep Any help is welcome! I'm trying following [this tutorial](https://dzone.com/articles/publish-your-artifacts-to-maven-central) but I think it a *bit* (or a lot) confusing. Should I put those maven plugins or not? Looking in Cactoos' `pom.xml` file there isn't any about them...

**Comment by amihaiemil** [comment]
@fabriciofx it will not apear in the search results instantly, the indexing at maven central is not in real time. Try pulling it as a maven dependency to see if it is published or not :)

**Comment by fabriciofx** [comment]
@amihaiemil Do you know how many time maven central needs to index it? Because I think Yegor's Cactoos very fast. And other thing: what's the version of my library? My version says `<version>0.2-SNAPSHOT</version>` but the deployment show me `Uploading to oss.sonatype.org: https://oss.sonatype.org/content/repositories/snapshots/com/github/fabriciofx/cactoos-jdbc/0.2-SNAPSHOT/cactoos-jdbc-0.2-20181014.041022-1.jar`. How deploy my library with the same found at ``<version>0.2-SNAPSHOT</version>` ?

**Comment by skapral** [comment]
@fabriciofx in addition to deployment, you need also to approve the release at oss.sonatype.org. Have you done that?

**Comment by fabriciofx** [comment]
@skapral How can I do that?

**Comment by amihaiemil** [comment]
@fabriciofx 

> How deploy my library with the same found at ``0.2-SNAPSHOT

I'm not sure you can release an artifact with the ``-SNAPSHOT`` in its version. That is a convention for the development versions. 

For versioning, you have to remove the ``-SNAPSHOT``. Either use the ``mvn release`` lifecycle, or make a release script that will remove the ``-SNAPSHOT`` before actually executing the release plugins. 

As to what @skapral, I don't know if you have to approve anything in sonatype.org, as long as you made the right configs in pom.xml. See how I [release and version](https://www.amihaiemil.com/2018/09/30/project-versioning-with-rultor.html) my projects with Rultor (it is based on Yegor's tutorial for releaseing to Maven Central with Rultor). You can see how the configs are done (mvn -Prelease and rrv.sh) in docker-java-api for instance.

**Comment by skapral** [comment]
@fabriciofx  login to oss.sonatype.org, search for your release in "staging repositories" tab, choose it, click "close" (at these stage your artifacts will be validated for presence of some mandatory attributes). After a couple of minutes refresh the page, check that everything is okay and press "release".

**Comment by fabriciofx** [comment]
@skapral @smallcreep @amihaiemil Guys, thanks for the help! I don't know what I exactly did, but worked! Just for registration: to perform the deployment, jcabi-parent provides a `mnv clean deploy -Psonatype` that does the magic.
